nelmio_api_doc:
  documentation:
      servers:
        - url: https://127.0.0.1:8000
          description: Bilemo
      info:
          title: Bilemo Api
          description: Api officielle de Bilemo
          version: 1.0.0
      components:
          securitySchemes:
              Bearer:
                  type: http
                  scheme: bearer
                  bearerFormat: JWT
      security:
          - Bearer: []
  areas:
      path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
          - ^/api(?!/doc$)